### ISSUE TITLE
Some models fail in test_hepmc_io.py

### ISSUE THREAD

**Issue by jncots** [impy-project/chromo#67]
During reading from the file some models produces errors. It is unclear whether it is a problem of hepmc_io or a models by themselves. The models are marked as `pytest.xfail("The model SHOULD BE FIXED!!!")`.

**Comment by HDembinski** [comment]
I am not sure what you mean. I am looking at `master` and there we have `xfail_on_ci_if_model_is_incompatible(Model)`. We can remove this once we implement lazy downloading of large data tables.

**Comment by HDembinski** [comment]
The error message is different: pytest.xfail("model cannot succeed on CI, because git lfs does not work")

**Comment by HDembinski** [comment]
I looked into this. There are two issues at least.

- The main issue seems to be that calling `to_hepmc3` triggers some infinite loop so that the process does a timeout. Most models pass if you just run `expected = run_in_separate_process(run, Model, timeout=30)` 
- However, Sibyll23c and Sibyll23d do not even pass this. They already fail if you call event.copy() which `return list(gen(3)` does implicitly.

When did this start to fail? These tests used to work in the past, no? We run these tests on every PR precisely to detect whether code changes break stuff.

**Comment by afedynitch** [comment]
@HDembinski @jncots could this be related to the PR #73 ?

**Comment by HDembinski** [comment]
In case of DpmjetIII193, Phojet112, Phojet191, Phojet193 it seems to be an error in pyhepmc, because it cannot read an event back in that was written before.

**Comment by HDembinski** [comment]
Looks like HepMC3 C++ chokes on lines like this 
`V -5 0 [] @ 1.6841757751905629e-12 -8.2723073087782771e-13 8.2361866834209819e-13 0.0000000000000000e+00`

**Comment by HDembinski** [comment]
Andrii already answered. He says that vertices which have no incoming particles are not allowed. The AsciiWriter does not complain when it gets this input, but the AsciiReader does.

**Comment by HDembinski** [comment]
Having vertices without incoming particles is perhaps something that should be fixed in the models, then.

**Comment by afedynitch** [comment]
Do you have printout or at least the pid's of this event? I think that this might be the case for some radiation processes (FSR), or gluon kinks.

**Comment by HDembinski** [comment]
Thanks to the pyhepmc update, we now get proper exceptions, see https://github.com/impy-project/impy/actions/runs/3202902221/jobs/5232372840#step:7:319

**Comment by HDembinski** [comment]
@afedynitch I think the easiest for you is to checkout my PR https://github.com/impy-project/impy/pull/74, compile it, and run `python -m pytest -k test_to_hepmc3'[DPMJetIII191]' --pdb` which brings you right to point of failure. You can inspect the event in the debugger.

**Comment by afedynitch** [comment]
Great! Thanks @HDembinski. I'll test this asap.

**Comment by afedynitch** [comment]
To refresh this one here.... I'm (almost) certain that there is no way in DPMJET that an entry can have more than 2 parents. So, the indices parent indices are not ranges. The entries are added in order in some of the routines and the way the routine is written it adds 5 then 6, then does something to 5 and puts and updated version in 7, then takes 6 and does something to it puts it on 8. This causes the apparent overlap, which is not a real overlap.

Is there any solution on the pyhepmc side? I tried changing this in DPMJET but it's a Ranft-style routine and not trivial to implement this. (The trivial attempts mess it up...).

**Comment by HDembinski** [comment]
Let's zoom about this so I better understand what you mean and what needs to be changed. Perhaps I can fix this in pyhepmc, perhaps we can fix it in MCEvent.

**Comment by HDembinski** [comment]
We sorta fixed this, so I removed the "bug" label. I think this can be closed, since we have warnings in place in the code as reminders that this was only fixed with a workaround for the offending models, but not the fundamental issue.

**Comment by afedynitch** [comment]
@HDembinski Do I understand correctly that the temporary fix is to disable the history for the relevant models DPMJET and UrQMD? I doubt anything can be fixed in UrQMD, although I could look at it at some point. For DPMJET, the issue is identified but it is a disagreement of the logic between DPMJET and pyhepmc (parents are pointers to particles not ranges).

**Comment by HDembinski** [comment]
Yes, but the temporary fix is minimal invasive: when you convert the event to a HepMC3 GenEvent (necessary to write it to disk with pyhepmc, and for visualization in Jupyter notebooks), then the parent info is deleted in the GenEvent. The parent info is untouched in the EventData object.

> For DPMJET, the issue is identified but it is a disagreement of the logic between DPMJET and pyhepmc (parents are pointers to particles not ranges).

We don't need to change the fortran code of DPMJet, however, the Python class DPMJetIII should make the necessary transformations so that DPMJet follows the established Pythia6/Pythia8 convention, if that's at all possible. It is the job of impy to unify the input and output of generators. We cannot have one generator set parents in a different way from all the others.

**Comment by jncots** [comment]
See #101 and #170. #170 partly improved problem with parents in DPMJet , but not completely solved.
